export const ADD_SQUATS_TOTAL = 'ADD_SQUATS_TOTAL ';
export const ADD_SQUAT_SESSION = 'ADD_SQUAT_SESSION ';
export const RESET_SQUATS_SESSION = 'RESET_SQUATS_SESSION ';
export const IS_CONNECTED = 'IS_CONNECTED ';
